### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Chingk26** [yy6768/PetBackend#35]
**描述Bug**
无法运行

**复现步骤**
步骤以复现bug:

**预期行为**
无法启动PetWebbackend

**截图**
<img width="1280" alt="57e47ddfc1d335c28248ff2981f0551" src="https://github.com/yy6768/PetBackend/assets/145654790/f22a2107-348e-483a-9787-f4fa7cb3f271">

##### 附加上下文

**Comment by yy6768** [comment]
solve in #34
